version: '3'
services:
  app:
    build: .
    ports:
      - '8000:8080'
    volumes:
      - ./packers_news:/work/packers_news
      # Firestoreなどを利用する場合は認証キーを入れる
      # - ./credentials.json:/work/credentials.json
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/work/credentials.json
    command: >
      uvicorn packers_news.main:app
      --host 0.0.0.0
      --port 8080
      --reload
