version: 2.1

orbs:
  python: circleci/python@0.2.1
  slack: circleci/slack@3.4.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      # githubからソースを持ってくる
      - checkout
      # キャッシュの読み込み。意味があるのかはまだ理解してない
      - python/load-cache
      - run:
          command: |
            pip install pipenv
            pipenv install --dev
          name: install dependencies
      # キャッシュの保存。意味があるのかはまだ理解してない
      - python/save-cache
      - run:
          command: |
            pipenv run python -m pytest --junitxml=test-results/junit.xml
          name: run test
      - run:
          command: |
            pipenv run python -m pytest --cov=packers_news --cov-report=xml:test-results/cov.xml
          name: run test-cov
      # テストサマリーに表示するテスト結果をアップロードします
      # https://circleci.com/ja/docs/2.0/collect-test-data/
      - store_test_results:
          path: test-results
      - slack/status:
          fail_only: true
          mentions: 'kobori'
          webhook: $SLACK_DEVELOPMENT_WEBHOOK
workflows:
  main:
    jobs:
      - build-and-test
